import type { ReportCard } from "./types"

export const mockReportCards: ReportCard[] = [
  {
    id: "1",
    studentId: "STU001",
    studentName: "John Doe",
    rollNumber: "001",
    className: "10A",
    semester: "1",
    academicYear: "2024-2025",
    totalMarks: 480,
    totalPercentage: 96,
    remarks: "Excellent performance. Keep up the good work!",
    teacherName: "Ms. Sarah Johnson",
    principalName: "Dr. Robert Smith",
    issuedDate: "2024-12-15",
    grades: [
      {
        subjectId: "1",
        subjectName: "Mathematics",
        marks: 95,
        totalMarks: 100,
        percentage: 95,
        grade: "A+",
      },
      {
        subjectId: "2",
        subjectName: "English",
        marks: 92,
        totalMarks: 100,
        percentage: 92,
        grade: "A+",
      },
      {
        subjectId: "3",
        subjectName: "Science",
        marks: 98,
        totalMarks: 100,
        percentage: 98,
        grade: "A+",
      },
      {
        subjectId: "4",
        subjectName: "Social Studies",
        marks: 88,
        totalMarks: 100,
        percentage: 88,
        grade: "A",
      },
      {
        subjectId: "5",
        subjectName: "Physical Education",
        marks: 95,
        totalMarks: 100,
        percentage: 95,
        grade: "A+",
      },
    ],
  },
  {
    id: "2",
    studentId: "STU002",
    studentName: "Emily Smith",
    rollNumber: "002",
    className: "10A",
    semester: "1",
    academicYear: "2024-2025",
    totalMarks: 440,
    totalPercentage: 88,
    remarks: "Good performance. Focus on science subjects.",
    teacherName: "Ms. Sarah Johnson",
    principalName: "Dr. Robert Smith",
    issuedDate: "2024-12-15",
    grades: [
      {
        subjectId: "1",
        subjectName: "Mathematics",
        marks: 85,
        totalMarks: 100,
        percentage: 85,
        grade: "A",
      },
      {
        subjectId: "2",
        subjectName: "English",
        marks: 90,
        totalMarks: 100,
        percentage: 90,
        grade: "A+",
      },
      {
        subjectId: "3",
        subjectName: "Science",
        marks: 80,
        totalMarks: 100,
        percentage: 80,
        grade: "A",
      },
      {
        subjectId: "4",
        subjectName: "Social Studies",
        marks: 92,
        totalMarks: 100,
        percentage: 92,
        grade: "A+",
      },
      {
        subjectId: "5",
        subjectName: "Physical Education",
        marks: 93,
        totalMarks: 100,
        percentage: 93,
        grade: "A+",
      },
    ],
  },
  {
    id: "3",
    studentId: "STU003",
    studentName: "Michael Johnson",
    rollNumber: "003",
    className: "10B",
    semester: "1",
    academicYear: "2024-2025",
    totalMarks: 410,
    totalPercentage: 82,
    remarks: "Average performance. Needs improvement in Mathematics.",
    teacherName: "Mr. James Wilson",
    principalName: "Dr. Robert Smith",
    issuedDate: "2024-12-15",
    grades: [
      {
        subjectId: "1",
        subjectName: "Mathematics",
        marks: 75,
        totalMarks: 100,
        percentage: 75,
        grade: "B+",
      },
      {
        subjectId: "2",
        subjectName: "English",
        marks: 85,
        totalMarks: 100,
        percentage: 85,
        grade: "A",
      },
      {
        subjectId: "3",
        subjectName: "Science",
        marks: 82,
        totalMarks: 100,
        percentage: 82,
        grade: "A",
      },
      {
        subjectId: "4",
        subjectName: "Social Studies",
        marks: 84,
        totalMarks: 100,
        percentage: 84,
        grade: "A",
      },
      {
        subjectId: "5",
        subjectName: "Physical Education",
        marks: 84,
        totalMarks: 100,
        percentage: 84,
        grade: "A",
      },
    ],
  },
]
